// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAalfO6-LafthYQr7OWy61C03hUemWUj2c',
    appId: '1:601184227211:web:a895ad085b458fe288698e',
    messagingSenderId: '601184227211',
    projectId: 'saveplate-kehlsteinhaus',
    authDomain: 'saveplate-kehlsteinhaus.firebaseapp.com',
    storageBucket: 'saveplate-kehlsteinhaus.firebasestorage.app',
    measurementId: 'G-ZTSZFMMWVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGytiwqIKneQNhKOD7htcD055AjSrnHG4',
    appId: '1:601184227211:android:f658a50a2c304a9988698e',
    messagingSenderId: '601184227211',
    projectId: 'saveplate-kehlsteinhaus',
    storageBucket: 'saveplate-kehlsteinhaus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCygvxxhlWAU47TE1ws01jatrM48yhlqaY',
    appId: '1:601184227211:ios:28a2f6cf96eea8cb88698e',
    messagingSenderId: '601184227211',
    projectId: 'saveplate-kehlsteinhaus',
    storageBucket: 'saveplate-kehlsteinhaus.firebasestorage.app',
    androidClientId: '601184227211-t3n2pa9i06sst2rm6ld53mg99t4pbthq.apps.googleusercontent.com',
    iosClientId: '601184227211-n79buii1vja65p0bil3sj8naf5hau3vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.savePlateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCygvxxhlWAU47TE1ws01jatrM48yhlqaY',
    appId: '1:601184227211:ios:28a2f6cf96eea8cb88698e',
    messagingSenderId: '601184227211',
    projectId: 'saveplate-kehlsteinhaus',
    storageBucket: 'saveplate-kehlsteinhaus.firebasestorage.app',
    androidClientId: '601184227211-t3n2pa9i06sst2rm6ld53mg99t4pbthq.apps.googleusercontent.com',
    iosClientId: '601184227211-n79buii1vja65p0bil3sj8naf5hau3vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.savePlateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAalfO6-LafthYQr7OWy61C03hUemWUj2c',
    appId: '1:601184227211:web:891721a93547720d88698e',
    messagingSenderId: '601184227211',
    projectId: 'saveplate-kehlsteinhaus',
    authDomain: 'saveplate-kehlsteinhaus.firebaseapp.com',
    storageBucket: 'saveplate-kehlsteinhaus.firebasestorage.app',
    measurementId: 'G-CN750TMNN5',
  );

}